---
title: Een eenvoudige electronica-uitbreiding aan Scratch toevoegen
hero_image: images/banner.png
description: Hoe je een eenvoudige electronica-uitbreiding aan Scratch toevoegd
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: De eenvoudige elektronica-uitbreiding toevoegen
