---
title: Adding the Simple Electronics extension to Scratch
hero_image: images/banner.png
description: Hoe voeg je de Pi GPIO-uitbreiding toe aan aan Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Voeg de Pi GPIO-uitbreiding toe
