---
title: Ychwanegu'r estyniad Pi GPIO i Scratch
hero_image: images/banner.png
description: Sut i ychwanegu'r estyniad Pi GPIO i Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Ychwanega'r estyniad Pi GPIO
