---
title: Adio'r estyniad Electroneg Syml i Scratch
hero_image: images/banner.png
description: Sut i adio'r estyniad Electroneg Syml i Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Adio estyniad Electroneg Syml
