---
title: Adding the Pi GPIO extension to Scratch
hero_image: images/banner.png
description: How to add the Pi GPIO extension to Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Add Pi GPIO extension
