---
title: Adicionando a extensão Simple Electronics ao Scratch
hero_image: images/banner.png
description: Como adicionar a extensão Simple Electronics ao Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Adicionar extensão Simple Electronics
