---
title: Ajouter l'extension Simple Electronics à Scratch
hero_image: images/banner.png
description: Comment ajouter l'extension Simple Electronics à Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Ajouter l'extension Simple Electronics
